# Build Spec for AWS CodeBuild CI

version: 0.2
env:
  variables:
    use_current_branch: "true"
    enable_smdataparallel_tests: "true"
    force_run_tests: "false"
    framework: "pytorch"
phases:
  install:
    commands:
      - apt-get update
      - apt-get install sudo -qq -o=Dpkg::Use-Pty=0
      - sudo apt-get install unzip -qq -o=Dpkg::Use-Pty=0
      - pip install -q -r config/profiler/requirements.txt
  build:
    commands:
      - chmod +x config/profiler/run_profiler_integration_tests.sh && ./config/profiler/run_profiler_integration_tests.sh
