# Build Spec for AWS CodeBuild CI

version: 0.2
env:
  variables:
    check_alarm_retries: "3"
    check_alarm_interval: "300"

phases:
  install:
    commands:
      - apt-get update
      - apt-get install sudo -qq -o=Dpkg::Use-Pty=0
      - sudo apt-get install unzip -qq -o=Dpkg::Use-Pty=0
      - pip install --upgrade pip==19.3.1
      - cd $CODEBUILD_SRC_DIR  && chmod +x config/protoc_downloader.sh && ./config/protoc_downloader.sh && cd ..
      - pip install -q pytest wheel pyYaml pytest-html pre-commit awscli pytest-cov
      - cd $CODEBUILD_SRC_DIR/benchmarks/scripts/pytorch && mkdir -p data && aws s3 cp s3://smdebug-testing/datasets/cifar-10-python.tar.gz data/cifar-10-batches-py.tar.gz
      - cd $CODEBUILD_SRC_DIR/benchmarks/scripts/pytorch/data && tar -zxf cifar-10-batches-py.tar.gz
      # download and install sagemaker SDK
      - cd $CODEBUILD_SRC_DIR
      - mkdir -p smprofiler-setup-files
      - aws s3 cp --recursive s3://sm-profiler-external-preview/sdk/ smprofiler-setup-files
      - pip install smprofiler-setup-files/sagemaker-1.60.3.dev0.tar.gz -q
      # The following command will enable the SDK to use new profiler configs in the API
      - aws configure add-model --service-model file://smprofiler-setup-files/sagemaker-2017-07-24.normal.json --service-name sagemaker

  build:
    commands:
      # build pip wheel of the latest smdebug
      - cd $CODEBUILD_SRC_DIR  && python setup.py bdist_wheel --universal && pip install --force-reinstall dist/*.whl
      # Runs the smprofiler performance benchmark jobs
      - cd $CODEBUILD_SRC_DIR/dist &&  echo "./"`ls smdebug*` > $CODEBUILD_SRC_DIR/benchmarks/scripts/pytorch/requirements.txt
      - cd $CODEBUILD_SRC_DIR/dist &&  cp smdebug*  $CODEBUILD_SRC_DIR/benchmarks/scripts/pytorch/.
      - cd $CODEBUILD_SRC_DIR  && python benchmarks/run_pytorch_benchmarks.py --retries $check_alarm_retries --interval $check_alarm_interval

  post_build:
    commands:
      - if [ "$CODEBUILD_BUILD_SUCCEEDING" -eq 0 ]; then echo "ERROR BUILD FAILED " && exit 1 ; fi
      - if [ "$CODEBUILD_BUILD_SUCCEEDING" -eq 1 ]; then echo "INFO BUILD SUCCEEDED !!! " ; fi
