# Build Spec for AWS CodeBuild CI TF 2.7.1 CPU and GPU Containers
# Target Containers:
    # CPU Container: 763104351884.dkr.ecr.us-east-1.amazonaws.com/tensorflow-training:2.7.1-cpu-py38-ubuntu20.04-sagemaker
    # GPU Container: 763104351884.dkr.ecr.us-west-2.amazonaws.com/tensorflow-training:2.7.1-gpu-py38-cu112-ubuntu20.04-sagemaker-v1.0

# The PR CI Uses:
  # 763104351884.dkr.ecr.us-east-1.amazonaws.com/tensorflow-training:2.7.1-cpu-py38-ubuntu20.04-sagemaker

version: 0.2
env:
  variables:
    run_pytest_pytorch: "disable"
    run_pytest_mxnet: "disable"
    run_pytest_tensorflow: "disable"
    run_pytest_tensorflow2: "enable"
    run_pytest_xgboost: "disable"
    run_pytest_profiler: "enable"
    run_integration_pytest_pytorch: "disable"
    run_integration_pytest_mxnet: "disable"
    run_integration_pytest_tensorflow: "disable"
    run_integration_pytest_tensorflow2: "enable"
    run_integration_pytest_xgboost: "disable"
    # below needs to be enabled
    zero_code_change_test: "enable"
    # set code coverage flag
    code_coverage_smdebug: "true"
    build_type: "pr" # must be one of pr, nightly or release

phases:
  install:
    commands:
        -  . config/change_branch.sh
        - su && apt-get update
        - apt-get install sudo -qq -o=Dpkg::Use-Pty=0 # silence output: https://askubuntu.com/a/668859/724247
        - sudo apt-get update -qq -o=Dpkg::Use-Pty=0
        - sudo apt-get install unzip -qq -o=Dpkg::Use-Pty=0
        - pip install --upgrade pip==22.0.3
        - pip install -q matplotlib==3.3.1 seaborn==0.10.1 nbconvert==5.6.1 papermill==2.3.4 flaky==3.7.0 beautifulsoup4==4.8.2 jupyter==1.0.0 scipy==1.5.2 scikit-learn==0.23.2 bokeh==2.2.3 simplejson==3.17.2 transformers==4.2.1
        - pip install -q pytest wheel pytest-html pre-commit awscli pytest-cov

  pre_build:
    commands:
      - cd $CODEBUILD_SRC_DIR

  build:
    commands:
      - aws ssm get-parameters  --names deepenginepypipass
